### ISSUE TITLE
Issue with block policies

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#107]
Hello.

I am trying to setup a policy to check a specific ACL on NX-OX.

I have a configuration like this on the device for example

```
ip access-list admin
  10 permit ip 192.168.255.0/24 any
  20 permit ip 10.72.1.0 0.7.0.255 any
  30 permit ip 10.80.16.0/24 any
  40 permit ip 10.90.17.0/24 any
```

![image](https://user-images.githubusercontent.com/359877/112319896-cc04d900-8cae-11eb-8a8c-6f761ef7b9a9.png)

(tried with or without normalize)

I tried then the create the following policy that match exactly this but I cannot get it to comply I don't know why ?
When I only put the first line in the policy it complies but as soon as I add others it is failing to comply.

Am I doing something wrong ?

**Comment by SCadilhac** [comment]
This looks correct, but there might be some hidden space or special character... what about final carriage return?
Note: If you want to ensure that the ACL is present as it in the config, you should rather let the Context field empty, and paste the entire ACL (including `ip access-list admin`) into the main text field. Because with you current method, if Netshot doesn't find any `ip access-list admin` line, it will consider this as compiant.

**Comment by kedare** [comment]
Okay I found that the issues is that it needs the block to be indented in the field (so I need to add the spaces before each ACL element), is this normal ?

But when I put the whole thing inside as you said, as it is in the running configuration (so without the context), it is failing again

**Comment by SCadilhac** [comment]
> Okay I found that the issues is that it needs the block to be indented in the field (so I need to add the spaces before each ACL element), is this normal ?

Yes, normal
