### ISSUE TITLE
Checking re. Log4J

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#176]
Hi,

I'd like to check if netshot is affected with the Log4J Vulnerability.

Thanks,

**Comment by pizu** [comment]
Currently, we are on v0.16.3

Thanks

**Comment by SCadilhac** [comment]
Netshot uses SL4J with Logback. No Log4j 2.x core logger.
Due to JRadius dependencies, Log4j 1.x is included in the Netshot package in versions < 0.17.0. However, my understanding is that Log4j 1.x is not impacted (as long as the JMS appender is not used).
Thus based on the info I have, I'm not seeing Netshot affected by the given vulnerability.
Netshot 0.17.0 removes the Log4j 1.x indirect inclusion, just in case.

**Comment by pizu** [comment]
Thanks for the feedback.


am going to upgrade to v0.17.0 just to be safe, closing ticket.

thanks.

**Comment by uchihaitachi2** [comment]
Thanks for the feedback
