### ISSUE TITLE
FortiGate - new diff every iteration

### ISSUE THREAD

**Issue by pfunkylol** [netfishers-onl/Netshot#220]
Hello,

It appears the code below from Fortinet_FortiOS.js doesnt work properly since at every run a new diff is created since it detects that the salt for the passwords lines is being changed with every show command.

`var previousConfiguration = device.get("configuration");`
      `  if (typeof previousConfiguration === "string" &&`
                       ` removeChangingParts(previousConfiguration) === removeChangingParts(configuration)) {`
               ` config.set("configuration", previousConfiguration);`
       ` }`
       ` else {`
       `         config.set("configuration", configuration);`
      `  }`

**Comment by pizu** [comment]
That is normal as the FG firewall changes the enc each time you do a show
command, the key in reality is not being changed.

**Comment by SCadilhac** [comment]
Indeed each time a FortiGate dumps out the running configuration, it uses a different salt to produce an encrypted version of the various secrets. Thus the FortiOS driver for Netshot has the following hack: using `removeChangingParts` function, it strips off all the encrypted (thus regenerated) parts from the config text before comparing the new configuration to the previous one: in case they are similar, it is assumed nothing has changed. This is an approximation: if only a password and nothing else was changed, the driver wouldn't see the delta at all.
If @pfunkylol you see a diff at each snapshot, there might be something wrong with the `removeChangingParts` hack on your configurations and/or FortiOS version.

**Comment by SCadilhac** [comment]
The driver doesn't remove the password hashes from the configuration that will be stored, it rather just temporary removes them when comparing the previous and current configurations. Otherwise the backup wouldn't contain the passwords at all and couldn't be re-injected as it. So whenever a real change is performed, the config diff will show the change and all passwords will look like being changed too.
Can you give a try with updated version? https://github.com/netfishers-onl/Netshot/commit/f851a89fdc61e7f8aa35f97eecdf368dc13ebc92

**Comment by pfunkylol** [comment]
At first glance appears to get the job done. I will keep an eye on it for a couple of days.
[INFO] The configuration hasn't changed. Not storing a new one in the DB.

Thanks
