### ISSUE TITLE
Issue with installation instructions

### ISSUE THREAD

**Issue by p4cketw0lf** [netfishers-onl/Netshot#267]
In step 2 of installation instructions .16 or more.

```
user@netshot:~$ sudo /usr/lib/jvm/graalvm/bin/gu install python
Downloading: Release index file from [oca.opensource.oracle.com](http://oca.opensource.oracle.com/)
Error: Error reading component list: https://oca.opensource.oracle.com/gds/meta-data.json

```
not sure how to handle this error

**Comment by mcyclone** [comment]
you can use GraalVM CE 22.2.0 

GRAALVER="22.2.0"

**Comment by SCadilhac** [comment]
The next release of Netshot will work with a newer version of GraalVM.
For 0.18.x I've not tested another version than 21.3.0.
The Python component is not absolutely necessary (if you don't plan to use Python scripts).
You can still install it by manually downloading the package:

```bash
wget https://github.com/oracle/graalpython/releases/download/vm-21.3.0/python-installable-svm-java11-linux-amd64-21.3.0.jar
sudo /usr/lib/jvm/graalvm/bin/gu -L install ./python-installable-svm-java11-linux-amd64-21.3.0.jar
```

**Comment by anli77** [comment]
For those that like me find this, to install python the LLVM toolchains is also needed, and since meta-data.json file is no longer available, the LLVM module also fails, so this added to our docker spec fixed that.
`
RUN curl -L https://github.com/oracle/graalpython/releases/download/vm-$GRAALVER/python-installable-svm-java11-linux-amd64-$GRAALVER.jar --remote-name
RUN curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVER/llvm-toolchain-installable-java11-linux-amd64-$GRAALVER.jar --remote-name
RUN /usr/lib/jvm/graalvm/bin/gu -L install -D llvm-toolchain-installable-java11-linux-amd64-$GRAALVER.jar
RUN /usr/lib/jvm/graalvm/bin/gu -L install -D python-installable-svm-java11-linux-amd64-$GRAALVER.jar
`

Tested to work on 21.3.0, using GraalVM 22.2.0 did not work for us.

**Comment by SCadilhac** [comment]
Netshot 0.19 now using new version of GraalVM JRE, the install guide has been updated.
